# Generated by Django 3.1.7 on 2021-03-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
