# Generated by Django 3.1.7 on 2021-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oob', '0007_auto_20210323_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
